NAME = libftprintf.a
SRC = ft_printf.c ft_parse_flags.c \
	ft_handle_char.c ft_handle_str.c ft_handle_int.c \
	ft_handle_unsigned.c ft_handle_hex.c ft_handle_ptr.c
OBJ = $(SRC:.c=.o)
CC = cc
CFLAGS = -Wall -Wextra -Werror
AR = ar rcs

all: $(NAME)

$(NAME): $(OBJ)
	$(AR) $(NAME) $(OBJ)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all
